name: Descenders
main: chmilk.descenders.Descenders
version: 0.0.1
description: Dungoneering Plugin
api-version: 1.16

commands:
  fillchest:
    description: "test command to fill a chest"
  emptychest:
    description: "test command to empty a chest"
  summonthegodslayer:
    description: "thou wishes to kill a god???"
    usage: "Usage /<command>"
  summontrident:
    description: "thou wishes to kill a god???"
    usage: "Usage /<command>"
  summonfunnystick:
    description: "thou wishes to kill a god???"
    usage: "Usage /<command>"
  addchest:
    description: "Add chest to a dungeon's loot list"
    usage: "Usage /<command> [dungeon name]"
  removechest:
    description: "Remove a chest from a dungeon's loot list"
    usage: "Usage /<command> [dungeon name]"
  printLootSpots:
    description: "Prints loot spots for a given dungeon"
    usage: "Usage /<command> [dungeon name]"
  fillLootSpots:
    description: "Fills the loot spots of a dungeon"
    usage: "Usage /<command> [dungeon name]"
  emptyLootSpots:
    description: "Empties the loot spots of a dungeon"
    usage: "Usage /<command> [dungeon name]"
  saveDungeon:
    description: "Saves a given dungeon to a file"
    usage: "Usage /<command> [dungeon name]"
  reloadDungeon:
    description: "reloads a dungeon from a file"
    usage: "Usage /<command> [dungeon name]"
  clearDungeon:
    description: "clears the loot spots in a dungeon"
    usage: "Usage /<command> [dungeon name]"